### ISSUE TITLE
求带

### ISSUE THREAD

**Issue by zengwei2016** [java-a/lab0#17]
不会

**Comment by lfs1102** [comment]
接下去戴老师和我们三位助教会给大家慢慢教授Java语言，我相信很快你就能学会用Java编程了！

**Comment by zengwei2016** [comment]
谢谢

在2016-09-06 21:31:49，Fengshuang Linotifications@github.com写道：

接下去戴老师和我们三位助教会给大家慢慢教授Java语言，我相信很快你就能学会用Java编程了！
